apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskphp
spec:
  selector:
    matchLabels:
      env: production
  replicas: 3
  template:
    metadata:
      labels:
        env: production
    spec:
      containers:
      - name: html-deploy
        image: vimal13/apache-webserver-php
	ports:
        - containerPort: 80
        volumeMounts:
          - name: web
            mountPath: /var/www/html   
      volumes:
      - name: web
        persistentVolumeClaim:
          claimName: web
